### ISSUE TITLE
steam oauth

### ISSUE THREAD

**Issue by yblackd** [Bubbet/DiscordSteamOAuth2Bot#1]
关于steam oauth，
```python
OAUTH2_CLIENT_ID = os.getenv('OAUTH2_CLIENT_ID')
场景：web开发对接steam使用内购和steam云，但是steam的web api 需要oauth验证通过才可以，但是我找不到oauth接口的参数client id.下面是接口：
https://steamcommunity.com/oauth/login?response_type=token&client_id=client_id_here&state=whatever_you_want
```

`OAUTH2_CLIENT_ID这个参数从哪里获得的？是在steamworks创建应用时拿到的？还是？`

```html
steamworks Documents：是这样写的，
To use OAuth, first you will need to obtain a Client ID from Valve. See Getting Started for more detail.
但是我没有找到 从哪里获取这个 client id参数
```

可以分享一下经验吗？谢谢

**Comment by Bubbet** [comment]
This application never interacted with the steamworks api. It simply used the discord oauth2 to access a discord users connected accounts and store their steam-id if they have one connected.

**Comment by yblackd** [comment]
hello ，at first，thank you very much your answer.  but I do not understand. Now I want to implement the list of steam cloud, add, delete and modify functions! OAuth validation is required before using the Steamworks API. What can I do without verifying that I can't use it?重发自我的华为手机-------- 原始邮件 --------发件人： Bubbet <notifications@github.com>日期： 2020年6月15日周一 半夜11:34收件人： Bubbet/DiscordSteamOAuth2Bot <DiscordSteamOAuth2Bot@noreply.github.com>抄送： yblackd <yblackd@163.com>, Author <author@noreply.github.com>主    题： Re: [Bubbet/DiscordSteamOAuth2Bot] steam oauth (#1)
This application never interacted with the steamworks api. It simply used the discord oauth2 to access a discord users connected accounts and store their steam-id if they have one connected.

**Comment by Bubbet** [comment]
This app does not use steamworks, I'm not able to help you with steamworks related issues.

**Comment by yblackd** [comment]
hello friend

ok! i understand, thank you very much for your answers.



At 2020-06-15 23:34:53, "Bubbet" <notifications@github.com> wrote:

This application never interacted with the steamworks api. It simply used the discord oauth2 to access a discord users connected accounts and store their steam-id if they have one connected.
